### ISSUE TITLE
Bool expressions and not single operator operations fails 

### ISSUE THREAD

**Issue by gwaldvogel** [Quick-Turn-Studio/CLionSupportForQt#12]
The following code produces this error at `||`: `QmlTokenType.CLOSE_PARENTHESIS, QmlTokenType.DOT, QmlTokenType.INCREMENT_OPERATOR or QmlTokenType.OPEN_ARRAY expected, got '||'`

Code to reproduce:
```
Keys.onPressed: {
            console.log("Key pressed", event.key, event)
            if(event.key === Qt.Key_Left || event.key === Qt.Key_A) {
                player.moveLeft();
            }
}
```

Just to clarify: this is an issue with the QML Editor.

**Comment by machtelik** [comment]
Same with `&&` which leads to `QmlTokenType.CLOSE_PARENTHESIS, QmlTokenType.COMPARE_OPERATOR, QmlTokenType.DOT, QmlTokenType.INCREMENT_OPERATOR or QmlTokenType.OPEN_ARRAY expected, got '&&'`

**Comment by grabusr** [comment]
Hi @gwaldvogel

We finally was managed to recreate parser and issues with operations should not happen again. Version 0.9.8 is ready to download. Please let us know if it solves this issue.
