### ISSUE TITLE
Qrc QML Import Path

### ISSUE THREAD

**Issue by vaclav-seidl** [Quick-Turn-Studio/CLionSupportForQt#16]
QML engine supports importing QML files from Qt resources file (e.g. `import "qrc:/qt-project.org/imports"`) as described in [the documentation](https://doc.qt.io/qt-5/qtqml-syntax-imports.html#qml-import-path).

This fails with `QmlTokenType.FOLDER_PACKAGE_NAME or QmlTokenType.PACKAGE_NAME expected, got '"'` and usually breaks syntax for the rest of the file.

**Comment by grabusr** [comment]
Hi Václav,

Version 0.9.3 with a fix for that is available to download. Please confirm if it solves the issue.

**Comment by vaclav-seidl** [comment]
Hi, I can confirm it has been indeed fixed.
Thank you!
