### ISSUE TITLE
_ shouldn't be a problem in a url

### ISSUE THREAD

**Issue by Zocress** [Quick-Turn-Studio/CLionSupportForQt#17]
Hey, I get a highlight with an error ')' expected, got '_', but _ is just part of the local directory. There is no way to ignore this and it is painfully highlighted.

**Comment by grabusr** [comment]
Hello Zocress,

Could you provide a code example with that bug?

**Comment by Zocress** [comment]
[image: Capture.PNG]

Den man. 14. sep. 2020 kl. 19.44 skrev Slawomir Grabowski <
notifications@github.com>:

**Comment by grabusr** [comment]
Zocress, it seems that reponding by email did not handle sending image. Could you send us code snippet in text format?

**Comment by Zocress** [comment]
QRadioButton::indicator {
    image: url(//10.10.200.12/_tgbvfx/_bin/PublishTool/1.0/graphics/QRadioButton_unchecked.png);
    height: 17px;
    width: 17px;
}

QRadioButton::indicator:hover {
    image: url(//10.10.200.12/_tgbvfx/_bin/PublishTool/1.0/graphics/QRadioButton_unchecked_hover.png);
    height: 17px;
    width: 17px;
}

QRadioButton::indicator:on {
    image: url(//10.10.200.12/_tgbvfx/_bin/PublishTool/1.0/graphics/QRadioButton_checked.png);
    height: 17px;
    width: 17px;
}

QRadioButton::indicator:on:hover {
    image: url(//10.10.200.12/_tgbvfx/_bin/PublishTool/1.0/graphics/QRadioButton_checked_hover.png);
    height: 17px;
    width: 17px;
}


Den tir. 15. sep. 2020 kl. 09.54 skrev Slawomir Grabowski <
notifications@github.com>:

**Comment by grabusr** [comment]
Hi Zocress,

We uploaded new 0.1.6 version with fix for that issue. Please confirm if it resolves your problem.

**Comment by Zocress** [comment]
It does resolve the url issue, but I've added '%PATH%' to my url's and
replace them in python to do relative paths and that also turns everything
pink.

[image: image.png]

Den fre. 9. okt. 2020 kl. 17.31 skrev Slawomir Grabowski <
notifications@github.com>:

**Comment by grabusr** [comment]
Could you place the code snippet inside the post? Putting the image sometimes do not work, especially in cases when a response is performed by email.

**Comment by Zocress** [comment]
QComboBox::drop-down {
    border: none;
    width: 30px;
    height: 30px;
}

QComboBox::down-arrow {
    image: url(C:/Users/mah/Desktop/image.png);
}

QComboBox::down-arrow {
    image: url(%PATH%/graphics/QComboBox_dropdown_arrow.png);
    width 50px;
    height 50px;
}


/* Buttons */
QPushButton {
    color: white;
    font: bold 14px;
    background: #2a2a2b;
    border: none;
    border-radius: 20;
}


Den man. 12. okt. 2020 kl. 18.57 skrev Slawomir Grabowski <
notifications@github.com>:

**Comment by grabusr** [comment]
Hi Zocress,

We uploaded new 0.1.7 version with fix for that issue. Please confirm if it resolves your problem.
By the way, could you provide a link with documentation for this feature? I see this first time. Thanks!

**Comment by Zocress** [comment]
Hi Slawomir,

0.1.7 doesn't seem to be available for download at the moment through the
PyCharm's plugin manager.
It isn't a feature of QSS, but it's used for string parsing in python and
the reason the %PATH% is commonly used comes from Windows batch script.

Den ons. 14. okt. 2020 kl. 08.27 skrev Slawomir Grabowski <
notifications@github.com>:

**Comment by grabusr** [comment]
Yeah, I said that it will be available to download soon, because JetBrains marketplace perform plugin review every time that we upload the update. I hope it will be resolved tomorrow.

**Comment by Zocress** [comment]
Yep it is fixed now, works great. Thank you.

Best,
Mads

Den ons. 14. okt. 2020 kl. 18.44 skrev Slawomir Grabowski <
notifications@github.com>:
