### ISSUE TITLE
String interpolation breaks the syntax highlighting

### ISSUE THREAD

**Issue by agom** [Quick-Turn-Studio/CLionSupportForQt#18]
Using the string interpolation breaks the syntax highlighting for the rest of the file e.g. 
```
property string name: `String ${number}`
```
Tooltip error on the first ` character: 
```
<bool value>, <object>, <operation>, <ternary operation>, QmlTokenType.CLASS_NAME, QmlTokenType.FIELD_NAME, QmlTokenType.FUNCTION_NAME, QmlTokenType.IMPORT_QUALIFIER, QmlTokenType.INCREMENT_OPERATOR, QmlTokenType.INTEGER_VALUE, QmlTokenType.NAMESPACE_NAME, QmlTokenType.NEW_KEYWORD, QmlTokenType.NULL_KEYWORD, QmlTokenType.NUMBER_VALUE, QmlTokenType.OPEN_ARRAY, QmlTokenType.REFERENCE_NAME or QmlTokenType.STRING_VALUE expected, got '`'
```
Example screenshot

![image](https://user-images.githubusercontent.com/17353250/93991871-19020400-fd8d-11ea-879a-5ba4b99db5bd.png)

**Comment by grabusr** [comment]
Hi Agostino,
Version 0.9.4 is able to download. Please confirm if it solves your problems.

**Comment by agom** [comment]
> Hi Agostino,
> Version 0.9.4 is able to download. Please confirm if it solves your problems.

Seems to work, thanks!
