### ISSUE TITLE
String argument not supported

### ISSUE THREAD

**Issue by machtelik** [Quick-Turn-Studio/CLionSupportForQt#20]
Using string arguments like `text: "%1".arg("foo")` leads to error `<alias declaration>, <delegate declaration>, <property declaration>, <script field assignment>, <signal handler property>, <valued field assignment>, QmlTokenType.CLASS_NAME, QmlTokenType.CLOSE_BRACE, QmlTokenType.COMMAND_END, QmlTokenType.COMPARE_OPERATOR, QmlTokenType.COMPONENT_KEYWORD, QmlTokenType.ENUM_KEYWORD, QmlTokenType.FUNCTION_KEYWORD, QmlTokenType.ID_KEYWORD, QmlTokenType.IMPORT_QUALIFIER, QmlTokenType.OPERATION_OPERATOR or QmlTokenType.SIGNAL_KEYWORD expected, got '.'`

**Comment by grabusr** [comment]
Hi Mike,
Version 0.9.4 is able to download. Please confirm if it solves your problems.

**Comment by machtelik** [comment]
Seems to be solved, thanks.
