### ISSUE TITLE
'switch' property assignment syntax

### ISSUE THREAD

**Issue by machtelik** [Quick-Turn-Studio/CLionSupportForQt#21]
Having a construct like the following 

```
Text {
    text: switch (value) {
        case a:
            return "foo"
        default:
            return "bar"
    }
}
```

leads to error:
`<alias declaration>, <delegate declaration>, <property declaration>, <script field assignment>, <signal handler property>, <valued field assignment>, QmlTokenType.CLASS_NAME, QmlTokenType.CLOSE_BRACE, QmlTokenType.COMMAND_END, QmlTokenType.COMPARE_OPERATOR, QmlTokenType.COMPONENT_KEYWORD, QmlTokenType.DOT, QmlTokenType.ENUM_KEYWORD, QmlTokenType.FUNCTION_KEYWORD, QmlTokenType.ID_KEYWORD, QmlTokenType.IMPORT_QUALIFIER, QmlTokenType.OPERATION_OPERATOR, QmlTokenType.SIGNAL_KEYWORD or QmlTokenType.TERNARY_OPERATOR expected, got '{'`

**Comment by machtelik** [comment]
Here are a few more constructs leading to syntax errors:

```
Image {
	property string foo: "a"
	readonly property string bar: "a"

	source: {
		switch (foo) {
			case bar:
				return "qrc:///a.svg"
			default:
				return "qrc:///a.svg"
		}
	}
}

Image {
	fillMode: switch(foo) {
		case Foo:
			return Image.PreserveAspectFit
		default:
			return Image.PreserveAspectCrop
	}
}

Item {
	property var c: if (a !== undefined) a
}

Item {
	readonly property alias a: image.source
}

Item {
	id: text
	text: Style.text.foo
}

```

**Comment by grabusr** [comment]
Hi Mike
Version 0.9.4 is able to download. Please confirm if it solves your problems.

**Comment by machtelik** [comment]
```
Item {
	id: text
	text: Style.text.foo
}
```
still leads to: `QmlTokenType.CLASS_NAME, QmlTokenType.FIELD_NAME or QmlTokenType.IMPORT_QUALIFIER expected, got 'text'` seems to be a problem, if the identifier starts with an uppercase letter.

```
Item {
    width: 2 * -(1/2)
}
```
now leads to: `QmlTokenType.CLOSE_PARENTHESIS, QmlTokenType.COMPARE_OPERATOR, QmlTokenType.LOGIC_OPERATOR or QmlTokenType.TERNARY_OPERATOR expected, got '/'`.

```
Item {
	property var a: 2 < 2 - 1
}
```
leads to `QmlTokenType.TERNARY_OPERATOR expected, got '-'` similar to one of the following
```
Item {
	property var a: 2 < (2 - 1)
	//visible: 2 < (2 - 1)
	//visible: 2 < 2 - 1
	//width: visible ? (1 + 2) : 0
	//property var foo: (visible ? qsTr("Hello") + (selected ? qsTr("World") : qsTr("Foo") ) : qsTr("Bye"))
}
```
