### ISSUE TITLE
[Qt Style Sheet Highlighter] Boolean property not accepted 

### ISSUE THREAD

**Issue by std-any-emplace** [Quick-Turn-Studio/CLionSupportForQt#23]
This snippet is accepted by Qt5.1x, but Qt Style Sheet Highlighter accepts `false` only in quoted form.
```
QPushButton
{
	qproperty-flat: false;
}
```

**Comment by grabusr** [comment]
Hi,
Version 0.1.8 is ready to download. Please let's us know if it solves your problems.

**Comment by std-any-emplace** [comment]
Problem fixed in 0.1.8.
