### ISSUE TITLE
Add ability to comment lines using the `Comment with Line Comment` keybind  

### ISSUE THREAD

**Issue by Wubbzi** [Quick-Turn-Studio/CLionSupportForQt#26]
On Windows ctrl+/ will comment out a single line of code on the caret row or multiple lines if they are selected. It would be great to see this feature implemented in Qt Style Sheet Highlighter

**Comment by grabusr** [comment]
Hi Inigo,

Today we released Qt Style Sheets Editor. It is still in beta, but has already implemented commenting by pressing Ctrl + /:
https://plugins.jetbrains.com/plugin/16405-qt-style-sheets-editor

**Comment by Wubbzi** [comment]
I appreciate the update - It appears the comments are now working as expected.
