### ISSUE TITLE
Inline multiline comments

### ISSUE THREAD

**Issue by vaclav-seidl** [Quick-Turn-Studio/CLionSupportForQt#27]
Hi,

QML Editor 0.9.4 has a problem with multiline-style comments (`/* */`) 

How to reproduce:
```
Item {
        width: foo == 1 /* comment */ || foo == 2 /* comment */
    }
```

This is fine:
![image](https://user-images.githubusercontent.com/48297480/97068848-8f339980-15cb-11eb-8e70-dabec1f6ccad.png)

Adding second comment:
![image](https://user-images.githubusercontent.com/48297480/97068858-a4a8c380-15cb-11eb-9c67-1e762b3dd066.png)

This works:
![image](https://user-images.githubusercontent.com/48297480/97068878-c609af80-15cb-11eb-9b43-e5056616d456.png)

But this breaks:
![image](https://user-images.githubusercontent.com/48297480/97068885-d02bae00-15cb-11eb-9c79-d1976518b78b.png)

**Comment by grabusr** [comment]
Hi Václav,

Version 0.9.5 is ready to download. Please let us know if it solves your problem with comments.

**Comment by vaclav-seidl** [comment]
Hi, it works as expected, thank you!
