### ISSUE TITLE
Error when parsing event handlers Javascript code

### ISSUE THREAD

**Issue by agatti** [Quick-Turn-Studio/CLionSupportForQt#28]
The plugin seems to fail to parse some Javascript statements inside event handlers:

<img width="822" alt="Screenshot 2020-11-02 at 21 37 39" src="https://user-images.githubusercontent.com/235740/97916797-cb959100-1d53-11eb-8240-3fdfea28b9cc.png">

I managed to reproduce the error with as little made up code possible, but this occurs even on valid, working code.

I'm using v0.9.5-2019.3+ (which seems to be the latest at the moment) on PyCharm Professional 2020.2.3.

Is there any other information you need to further debug the issue?

**Comment by grabusr** [comment]
Hi Alessandro,

This is related to left recurssion problem with parsing operations. We are aware about this issue. We need to perform small architecture change, I think that we will be able to deliver fix for this soon.

**Comment by agatti** [comment]
I understand, thanks for the feedback.

Incidentally, is this the same issue as being unable to correctly parse qualified QML elements?  I do get this error which may be fixed by your coming changes but I'm not sure about that:

![Screenshot 2020-11-07 at 17 41 01](https://user-images.githubusercontent.com/235740/98446816-9b1d7080-2120-11eb-9477-be17e7d85879.png)

Should I file a new bug report for that?
