### ISSUE TITLE
PyCharm Qt Style Sheet Highlighter plugin - collapse Function

### ISSUE THREAD

**Issue by DragonflyNet67** [Quick-Turn-Studio/CLionSupportForQt#29]
First thanks a lot for this useful Plugin.
it would be nice if qss (css) Sections could be collapsed/uncollapsed.

**Comment by grabusr** [comment]
Hi Nelson,

Today we released Qt Style Sheets Editor. It is still in beta, but has collapsing already implemented:
https://plugins.jetbrains.com/plugin/16405-qt-style-sheets-editor
