### ISSUE TITLE
url parameter

### ISSUE THREAD

**Issue by fizzyade** [Quick-Turn-Studio/CLionSupportForQt#30]
Hi thanks for the plugin, a quick observation is that highlighting does not work correctly for the following situation regarding a url:

url('/my folder/fred@2x.png')

Firstly, it doesn't like the single quote (but this is required in my particular situation)

Secondly, it doesn't handle the @ properly, and renders the text in a different colour from the @ symbol.

<img width="553" alt="CleanShot 2020-11-13 at 22 14 27@2x" src="https://user-images.githubusercontent.com/55795671/99126254-b1826b00-25fd-11eb-9aa1-36cd1dece01b.png">

**Comment by grabusr** [comment]
Hi Adrian,

Version 0.1.9 is able to download. Please let us know if the fix solves your issues.

**Comment by fizzyade** [comment]
Yes!  That has fixed it :)

Thanks for fixing this and for your work.
