### ISSUE TITLE
large one line message after enabling the plugin 

### ISSUE THREAD

**Issue by Da-Viper** [Quick-Turn-Studio/CLionSupportForQt#31]
i just bought the plugin for qml for the store, after enabling it i get a long one line error 

`<alias declaration>, <delegate declaration>, <property declaration>, <script field assignment>, <signal handler property>, <valued field assignment>, QmlTokenType.CLASS_NAME, QmlTokenType.CLOSE_BRACE, QmlTokenType.COMMAND_END, QmlTokenType.COMPONENT_KEYWORD, QmlTokenType.ENUM_KEYWORD, QmlTokenType.FUNCTION_KEYWORD, QmlTokenType.ID_KEYWORD, QmlTokenType.IMPORT_QUALIFIER, QmlTokenType.SIGNAL_KEYWORD or QmlTokenType.TERNARY_OPERATOR expected, got '&&'`

on this line `visible: desktopBackground.winId !== 0 && mainWindow.configBlurBackground` when using the `&&` operator

**Comment by grabusr** [comment]
Hi,

Yes we are aware about this issue. It is related to not suport right recurssion in BNF JetBrains SDK. We work on this problem. It is already reported in #28.
