### ISSUE TITLE
False positive syntax error

### ISSUE THREAD

**Issue by skyronic** [Quick-Turn-Studio/CLionSupportForQt#34]
Some QML code I have isn't being highlighted properly. Here it is in CLion:

![image](https://user-images.githubusercontent.com/80173/106046610-7cd86880-60b0-11eb-8026-8a02d2517a48.png)

And the same in Qt Creator:

![image](https://user-images.githubusercontent.com/80173/106046651-89f55780-60b0-11eb-82e1-5de2342f3474.png)

**Comment by grabusr** [comment]
Hi Anirudh

Could you paste this code as text? I will be easier to reproduce this for use.

**Comment by skyronic** [comment]
Hi @grabusr here is the entire file:

https://github.com/pia-foss/desktop/blob/master/client/res/components/settings/pages/DedicatedIpList.qml

Our repository has a decent amount of QML with slightly more advanced (but valid) use cases. Feel free to check other files if there are syntax issues. Here are some other minor issues I noticed with the CLion Plugin (which are all valid code + work fine in Qt Creator)

![image](https://user-images.githubusercontent.com/80173/106311921-e5038780-6233-11eb-9527-4203d332e117.png)

> https://github.com/pia-foss/desktop/blob/master/client/res/components/settings/pages/DedicatedIpPage.qml#L65

![image](https://user-images.githubusercontent.com/80173/106312323-74a93600-6234-11eb-8ac7-c901610a6c34.png)

> https://github.com/pia-foss/desktop/blob/master/client/res/components/common/GenericButtonArea.qml#L58

![image](https://user-images.githubusercontent.com/80173/106314067-33665580-6237-11eb-8ee5-1b2336a7ce4d.png)

> https://github.com/pia-foss/desktop/blob/master/client/res/components/common/OneLinkMessage.qml#L49

![image](https://user-images.githubusercontent.com/80173/106314638-ffd7fb00-6237-11eb-9550-0f16b5a87c06.png)

> https://github.com/pia-foss/desktop/blob/master/client/res/components/common/OutlineFocusCue.qml#L29

![image](https://user-images.githubusercontent.com/80173/106314685-13836180-6238-11eb-9915-d3f34ab5ed6f.png)

> https://github.com/pia-foss/desktop/blob/master/client/res/components/common/OverlayDialog.qml#L84

**Comment by skyronic** [comment]
Hi @grabusr 

Do you have any estimate if/when some of these might be fixed? I'd be happy to test out a preview build if one is available!

**Comment by grabusr** [comment]
Hi Anirudh

We are so sorry about the late response. Currently we are overwhelmed by tasks. This week we have started to introduce new person that will support us in solving issues and extending our plugins.

**Comment by skyronic** [comment]
@grabusr No problem! Looking forward to see the updates!

**Comment by jgirardet** [comment]
I have same issue.
it looks like it appears with  strings.
![Screenshot_20210225_212051](https://user-images.githubusercontent.com/30120358/109212212-863c1a00-77af-11eb-8cbf-1688df3eb385.png)
![Screenshot_20210225_212232](https://user-images.githubusercontent.com/30120358/109212281-9ce27100-77af-11eb-95ea-693f7b710552.png)
commenting fix the error

**Comment by skyronic** [comment]
Thank you @grabusr ! Look forward to trying the fixed version!

**Comment by skyronic** [comment]
Hey @grabusr great work, most of the syntax issues are fixed! Some minor ones but I'll open separate issues for that. I'm going to close this since most pressing issues are fixed!

Happy to be a paying user! Looking forward to seeing more updates on this!
