### ISSUE TITLE
certain hex color combinations incorrectly show syntax highlighting error stripes

### ISSUE THREAD

**Issue by Wubbzi** [Quick-Turn-Studio/CLionSupportForQt#42]
The easiest way to recreate this issue is to add the code below into a qss file. Then select it by double-clicking the color and change the color to any 6 digit hexadecimal color code where the first digit is any number 0-9. After you make the change, you should see the error stripe below the integers you added at the beginning of the color code.

There have also been 1 or 2 instances where making these changes did not trigger an error stripe. Additionally, the error stripe will disappear after commenting and uncommenting the line.

```
QWidget {
    border: 1px solid #ABC123;
}
```
**After the change:**
![image](https://user-images.githubusercontent.com/5187375/114260147-a529f080-9998-11eb-916d-e765ad6b28bf.png)

Another instance can be seen when using any 3 digit color hex code. Even though there no examples of 3 digit hex colors on the official [StyleSheet Reference](https://doc.qt.io/qt-5/stylesheet-reference.html) there is a note under the Color example section that states: "The RGB colors allowed are the same as those allowed with CSS 2.1".

It appears the error stripe that shows up after this error does not disappear after a comment/uncomment. The only solution is to convert the color to 6 digits or to use a different method of defining the color. 

![image](https://user-images.githubusercontent.com/5187375/114260455-95aba700-999a-11eb-9f9e-b8d9496f6bf1.png)
 
Let me know if you need any other information to reproduce the errors.

**Comment by grabusr** [comment]
Hi Inigo,

Thank you for reporting this bug and well documented description with reproduction steps! We were able to fix it today. Now we are waiting for Jet Brains approval and we hope that the update will be available to download in the next two days.

**Comment by grabusr** [comment]
Hi Inigo,

Version 0.9.2 is able to download. Please let us know if this update solves this bug.

**Comment by Wubbzi** [comment]
Hey,

The new version is working as expected. Thanks for the super quick turnaround on this.
