### ISSUE TITLE
Error parsing qt6.0 import statements

### ISSUE THREAD

**Issue by spiderkeys** [Quick-Turn-Studio/CLionSupportForQt#45]
In Qt6, import statements do not require version numbers: https://wiki.qt.io/New_Features_in_Qt_6.0#Qt_QML

The plugin does not yet seem to parse the file correctly if the version is omitted.

**Comment by grabusr** [comment]
Hi Charles

Version 0.9.10 with a fix for this issue is uploaded and during JB review. It will be available to download soon.
