### ISSUE TITLE
Using `undefined` in a property declaration breaks parsing

### ISSUE THREAD

**Issue by bkarpati** [Quick-Turn-Studio/CLionSupportForQt#48]
QML editor version: 0.9.10-2020.3+
CLion versoion: 2021.2.1

It seems that using the `undefined` keyword in a property declaration breaks subsequent parsing. This can affect just the line itself or in extreme cases the entire rest of the file.

![image](https://user-images.githubusercontent.com/10961030/133093033-9d4e1f8d-4d33-4a24-9db9-065762f4c8a7.png)
Reported error: `QmlTokenType.CLOSE_BRACE or QmlTokenType.COMMAND_END expected, got '&'`

Extreme case:
![image](https://user-images.githubusercontent.com/10961030/133092893-6f3b3b3a-b9eb-449a-b322-99b3d7a9b151.png)
Reported error: `QmlTokenType.CLOSE_BRACE, QmlTokenType.CLOSE_PARENTHESIS or QmlTokenType.COMMAND_END expected, got ')'`

**Comment by grabusr** [comment]
Hi Bence

Finally we were able to rewrite QML Editor from scratch. Bug is fixed with 2023.1.0 version
