### ISSUE TITLE
I can not reopen my pycharm again after I installed this plugin

### ISSUE THREAD

**Issue by jingxunQ** [Quick-Turn-Studio/CLionSupportForQt#49]
The version of my system is `deepin 20.2`, the core depends `Linux 5.10.50-adm64-desktop`.  

The version of my pycharm is `pycharm-professional-2021.2.1`.  

One more important thing is that I had installed the other plugin named `QML Support`, the local file of it is `intellij-qml`

I just finished the installation, then I can find this plugin in my list, but there is a button in pycharm notified me that I need restart my pycharm. OK, I did it, the result is I am still stay at the interface like this:

![](https://i.imgur.com/oZ2oVjb.png)

So I killed the process, and restart it in terminal manually，but I can not reopen it either. Finally, I found the infomation of this problem in the picture below.

![](https://i.imgur.com/Cq92VXK.png)

But I have no idea with that how can I to fix it, so I have to remove the local file of this plugin to reopen my pycharm. 

All of above is the trouble I had got into. Is there anyone can give some good advice for me? thank you for everybody.

**Comment by grabusr** [comment]
Hi @jingxunQ 

Unfortunately, in JetBrains SDK there is no conflict checker to prevent that crashes. We could only put that info in description and implement application lifetime listener that looks for that kind of conflict, but it is not supported in every version of JB SDK.What should you do is go to plugins and disable/remove QML support plugin.
