### ISSUE TITLE
Better QML editor

### ISSUE THREAD

**Issue by kblinova** [Quick-Turn-Studio/CLionSupportForQt#5]
Current QML editor plug-in in Clion is not great. It would be nice to have a powerful QML editor similar to what QT Creator supports.

**Comment by grabusr** [comment]
Hello @kblinova.
Thank you for the request. The Creating QML Editor will be a nice challenge for us. Before saying "challenge accepted" we would like to measure the needs of the market. Could you share this post to help us collecting the votes to give us motivation for that investment?
* https://www.linkedin.com/feed/update/urn:li:activity:6656981921056202752

**Comment by mobius3** [comment]
Do want.

**Comment by orkusweb** [comment]
I would love to use CLion, but I really need QML. Currently I#m stuck to Qt Creator, which is a rather bad IDE, imo.

**Comment by grabusr** [comment]
Hello,

We released QML Editor 0.9! You can find it [here](https://quickturnstudio.com/QML-Editor).

**Comment by thawfeekyahya** [comment]
Is this plugin supports QML code navigation ?

**Comment by grabusr** [comment]
Not yet. We will implement this feature in next releases. @thawfeekyahya What part of the code navigation is the most important for you and you would like to see it first?
