### ISSUE TITLE
QSS marked with errors when adjusting sub control

### ISSUE THREAD

**Issue by Dariusz1989** [Quick-Turn-Studio/CLionSupportForQt#50]
This code >

QSplitter::handle::hover:horizontal {
    background: qlineargradient(x1: 0, y1: 1, x2: 1, y2: 1,
                                stop: 0.2 rgba(0,0,0,0),
                                stop: 0.4 #707070,
                                stop: 0.5 rgb(220,220,220),
                                stop: 0.6 #707070,
                                stop: 0.8 rgba(0,0,0,0));
}

Would cause it to go red.
The Hover:horizontal cause issue.

![image](https://user-images.githubusercontent.com/13185728/141643990-f56d9110-0d55-402a-a9e1-8a6042c3cedb.png)

Any chance we could fix this so that everything does not go red?

**Comment by grabusr** [comment]
Hi @Dariusz1989 

Is this happen on Qt Style Sheets Highlighter or Qt Style Sheets Editor?

**Comment by grabusr** [comment]
Hi @Dariusz1989, we uploaded version 0.9.3 with fix for this bug.
