### ISSUE TITLE
Not getting QML markdown highlighted

### ISSUE THREAD

**Issue by mbdaso** [Quick-Turn-Studio/CLionSupportForQt#51]
I installed the plugin but QML files are not being recognized

![image](https://user-images.githubusercontent.com/32129742/142829911-651b6f6e-dff3-44ee-ad61-4ca9335997f0.png)

**Comment by grabusr** [comment]
Hi @mbdaso 

The problem can appear if in the future you have chosen different editor in your IDE. To fix this you can go to menu:
File -> FileProperties -> Associate with File Type and then provide correct file pattern and choose QML file from list.

Please let us know if this fix your issue.
