### ISSUE TITLE
[Bug]: using block comments inside method call breaks formatting and parsing

### ISSUE THREAD

**Issue by zdanek** [Quick-Turn-Studio/CLionSupportForQt#60]
### Plugin

QML Editor

### Code example

// using block comments inside method call is allowed in QML (I'm using 5.x) but this breaks syntax parsing and highlighting
// look for /* clipToViewPort */
// code compiles so it's syntax is correct
// heavily used in for example QGroundControl
// https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/QGCMapPolygonVisuals.qml

    Component {
        id:  traceMouseAreaComponent

        MouseArea {
            anchors.fill:       mapControl
            preventStealing:    true
            z:                  QGroundControl.zOrderMapItems + 1   // Over item indicators

            onClicked: {
                if (mouse.button === Qt.LeftButton && _root.interactive) {
                    mapPolygon.appendVertex(mapControl.toCoordinate(Qt.point(mouse.x, mouse.y), false /* clipToViewPort */))
                }
            }
        }
    }

### Documentation reference

https://doc.qt.io/qt-6/qtqml-syntax-basics.html#comments

**Comment by grabusr** [comment]
Hi Bartek

Thank you for reporting this bug. We will look at this soon. We hope it will be quick fix, because currently we rewrite code parsing for QML code to support code completion.

**Comment by zdanek** [comment]
Thank you.
Also highlighting matched brackets - all types is a must as it  helps to
see the scope.

czw., 6 paź 2022, 23:56 użytkownik Slawomir Grabowski <
***@***.***> napisał:

**Comment by grabusr** [comment]
Hello Bartek.
Finally we uploaded new QML Editor with new syntax parser. Reported bug should be fixed.
