### ISSUE TITLE
[Bug]: Update for PyCharm 2022.3.1

### ISSUE THREAD

**Issue by runcode-git** [Quick-Turn-Studio/CLionSupportForQt#63]
### Plugin

Qt Style Sheets Editor

### Describe the bug

Hello, free version when will you update for PyCharm PyCharm 2022.3.1?
Thank you.

### Reproduction steps

update for PyCharm PyCharm 2022.3.1

**Comment by grabusr** [comment]
Hi

Hi, Some of used functions used are deprecated in JetBrains runtime 2022.3 and require some changes. Currently we focus our resources on rewriting QML Editor base. Qt Style Sheets Editor has different code base and is able to work with last JBR, so you can use it to work with *.qss files.
