### ISSUE TITLE
[Bug]: default qml syntax highlighting destroyed by plugin

### ISSUE THREAD

**Issue by bailleulj** [Quick-Turn-Studio/CLionSupportForQt#67]
### Plugin

QML Editor

### Describe the bug

If you install the plugin once, you will never be able to retrieve the Jetbrains QML features again.
There is a clear regression of what was present before. Destructing working environments is not acceptable.

### Reproduction steps

- QML plugin from jetbrains is quite unsatisfying, many features are proposed but don't work (usages, etc).
- disable it, install QML Editor plugin
- QML Editor has decent syntax highlighting, but very few features work.
- uninstall QML Editor
- enable jetbrains QML plugin again
- all features are unavailable now, 

No coloring at all, no syntax, nothing. Functions are no longer recognized, etc.
Qml becomes plain text

**Comment by grabusr** [comment]
Hi Jonathan

Unfortunately JB SDK does not support handling two plugins for same file extension, so you need to choose between QML Editor and JB plugin. In our code we do not disable/enable JB plugin. If you would like to enable JB plugin you need to go to Settings->Plugins and enable JB plugin again. If you would like to have enabled JB plugin automatically after disabling QML Editor you can raise an issue in JB issue tracker.

**Comment by bailleulj** [comment]
Hello grabusr,

As I wrote in the end of the description, I disabled your plugin and enabled JB plugin again. So only one running at once.
This is a real problem because now my profile is no longer able to deal with QML files with JB. 

I'm still trying to figure out how to salvage the profile in using spare profiles I have on other PCs.

**Comment by bailleulj** [comment]
As Anna Falevskaya precised to me, the problem is due to missing file association.
Assigning qml files to another plugin means you have to reassign file association once you uninstall the plugin.

In that case,
Settings>Editor>File Types, section QT modeling language, file name pattern must feature *.qml.

This worked fine for me, so indeed your plugin did not destroy anything in the JB profile. I guess the whole workflow deserves general clarifications though.
