### ISSUE TITLE
`palette` function is marked as error

### ISSUE THREAD

**Issue by droidmonkey** [Quick-Turn-Studio/CLionSupportForQt#9]
```
QPushButton:default {
    background: palette(highlight);
    color: palette(highlighted-text);
}
```

palette in the above is marked as an error, but is perfectly valid qss.

**Comment by grabusr** [comment]
Hello Jonathan, thank you for reporting this bug! We will fix it soon.

**Comment by droidmonkey** [comment]
Thanks, good work on these plug-ins BTW!

**Comment by grabusr** [comment]
Nice to hear that.
We uploaded new 0.1.4 version with a fix for the palette role support. Now we just wait for approval on JetBrains Marketplace.
Please let us know if it meets your needs.

**Comment by droidmonkey** [comment]
Tested and works well except for this case:

```
DatabaseOpenWidget #loginFrame {
    border: 2px groove palette(mid);
    background: palette(light);
}
```

**Comment by grabusr** [comment]
Yeah, also rgb(0, 0, 0) do not work as 3rd argument in border property.
Version 0.1.5 with fix for that is uploaded. Should be ready do download soon.
